#ifndef HAND_VIEW_DEFINES_H
#define HAND_VIEW_DEFINES_H


// Tags
#define ALIGNMENT        "Alignment"
#define ALTERNATE        "alternate"
#define BACK             "back"
#define BACKGROUND       "Background"
#define BUTTON           "Button"
#define CHILDREN         "Children"
#define COLOR            "Color"
#define CONTENT          "Content"
#define CONTROLID        "Control ID"
#define COORDINATES      "Coordinates"
#define DEFAULT          "Default"
#define DESCRIPTION      "Description"
#define DIM_FONT_MAX     "DIM_FONT_MAX"
#define DIM_FONT_PREFERRED "DIM_FONT_PREFERRED"
#define DRAWER           "Drawer"
#define ELEMENT          "Element"
#define EXECUTE          "execute"
#define FIELD            "Field"
#define FIELDS           "Fields"
#define FOCUS            "Focus"
#define FONT             "Font"
#define FRAME            "Frame"
#define FRAMEDLIST       "Framed list"
#define FULL             "full"
#define HORIZONTAL       "horizontal"
#define ICON             "Icon"
#define LAYER            "Layer"
#define LAYER_FACTORIES  "Layer Factories"
#define NAME             "Name"
#define PARENT           "Parent"
#define PREVIEW          "Preview"
#define RECT             "Rect"
#define RGB              "RGB"
#define SCALED           "scaled"
#define SCALEDHORIZONTAL "scaled horizontal"
#define SYSTEM           "System"
#define TARGET           "Target"
#define TEXT             "Text"
#define THEME            "Theme"
#define THEMES           "Themes"
#define USER             "User"
#define VERTICAL         "vertical"
#define VIEW             "View"


#endif // HAND_VIEW_DEFINES_H
